<?php

namespace Webkul\Admin\Exports\Dashboard;

use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithStrictNullComparison;
use Maatwebsite\Excel\Concerns\WithTitle;
use Webkul\Admin\Helpers\Dashboard;


class DashboardExport implements
    FromArray,
    ShouldAutoSize,
    WithStrictNullComparison,
    WithTitle
{
    /**
     * Create dashboard export.
     */
    public function __construct(
        protected Dashboard $dashboard,
        protected string $pipelineName,
        protected string $startDate,
        protected string $endDate,
        protected string $generatedBy
    ) {}

    /**
     * Data yang dimasukkan ke Excel.
     */
    public function array(): array
    {
        $revenue = $this->dashboard->getRevenueStats();

        $overall = $this->dashboard->getOverAllStats();

        $leadStats = $this->dashboard->getTotalLeadsStats();

        $rows = [
            ['CAPTURE IT CRM — DASHBOARD REPORT'],
            [],
            ['Date Range', "{$this->startDate} s/d {$this->endDate}"],
            ['Pipeline', $this->safeText($this->pipelineName)],
            ['Generated By', $this->safeText($this->generatedBy)],
            ['Generated At', now()->format('Y-m-d H:i:s')],
            [],
            ['SUMMARY'],
            ['Metric', 'Current', 'Previous', 'Change (%)'],

            $this->metricRow(
                'Won Revenue',
                data_get($revenue, 'total_won_revenue', []),
                true
            ),

            $this->metricRow(
                'Lost Revenue',
                data_get($revenue, 'total_lost_revenue', []),
                true
            ),

            $this->metricRow(
                'Average Lead Value',
                data_get($overall, 'average_lead_value', []),
                true
            ),

            $this->metricRow(
                'Total Leads',
                data_get($overall, 'total_leads', [])
            ),

            $this->metricRow(
                'Average Leads per Day',
                data_get($overall, 'average_leads_per_day', [])
            ),

            $this->metricRow(
                'Total Quotations',
                data_get($overall, 'total_quotations', [])
            ),

            $this->metricRow(
                'Total Persons',
                data_get($overall, 'total_persons', [])
            ),

            $this->metricRow(
                'Total Organizations',
                data_get($overall, 'total_organizations', [])
            ),
        ];

        $this->appendLeadOverTime(
            $rows,
            data_get($leadStats, 'all.over_time', []),
            data_get($leadStats, 'won.over_time', []),
            data_get($leadStats, 'lost.over_time', [])
        );

        $this->appendNamedTotals(
            $rows,
            'OPEN LEADS BY STAGE',
            'Lead Count',
            $this->dashboard->getOpenLeadsByStates()
        );

        $this->appendNamedTotals(
            $rows,
            'WON REVENUE BY SOURCE',
            'Revenue',
            $this->dashboard->getLeadsStatsBySources(),
            true
        );

        $this->appendNamedTotals(
            $rows,
            'WON REVENUE BY TYPE',
            'Revenue',
            $this->dashboard->getLeadsStatsByTypes(),
            true
        );

        $this->appendTopPersons(
            $rows,
            $this->dashboard->getTopPersons()
        );

        $this->appendTopProducts(
            $rows,
            $this->dashboard->getTopSellingProducts()
        );

        return $rows;
    }

    /**
     * Nama worksheet Excel.
     */
    public function title(): string
    {
        return 'Dashboard Report';
    }

    /**
     * Membuat satu baris statistik.
     */
    protected function metricRow(
        string $label,
        array $metric,
        bool $money = false
    ): array {
        $current = data_get($metric, 'current', 0);

        $previous = data_get($metric, 'previous', 0);

        if ($money) {
            $current = core()->formatBasePrice($current);

            $previous = core()->formatBasePrice($previous);
        }

        return [
            $label,
            $current,
            $previous,
            round(
                (float) data_get($metric, 'progress', 0),
                2
            ),
        ];
    }

    /**
     * Menambahkan statistik lead berdasarkan waktu.
     */
    protected function appendLeadOverTime(
        array &$rows,
        iterable $allItems,
        iterable $wonItems,
        iterable $lostItems
    ): void {
        $all = collect($allItems);

        $won = collect($wonItems)->keyBy('label');

        $lost = collect($lostItems)->keyBy('label');

        $rows[] = [];
        $rows[] = ['LEADS OVER TIME'];
        $rows[] = [
            'Period',
            'All Leads',
            'All Value',
            'Won Leads',
            'Won Value',
            'Lost Leads',
            'Lost Value',
        ];

        foreach ($all as $item) {
            $label = data_get($item, 'label', '');

            $wonItem = $won->get($label, []);

            $lostItem = $lost->get($label, []);

            $rows[] = [
                $this->safeText($label),

                (int) data_get($item, 'count', 0),

                (float) data_get($item, 'total', 0),

                (int) data_get($wonItem, 'count', 0),

                (float) data_get($wonItem, 'total', 0),

                (int) data_get($lostItem, 'count', 0),

                (float) data_get($lostItem, 'total', 0),
            ];
        }
    }

    /**
     * Menambahkan data dengan format nama dan total.
     */
    protected function appendNamedTotals(
        array &$rows,
        string $title,
        string $valueHeader,
        iterable $items,
        bool $money = false
    ): void {
        $rows[] = [];
        $rows[] = [$title];
        $rows[] = ['Name', $valueHeader];

        foreach ($items as $item) {
            $total = (float) data_get($item, 'total', 0);

            $rows[] = [
                $this->safeText(
                    data_get($item, 'name') ?: 'Unspecified'
                ),

                $money
                    ? core()->formatBasePrice($total)
                    : $total,
            ];
        }
    }

    /**
     * Menambahkan top persons.
     */
    protected function appendTopPersons(
        array &$rows,
        Collection $items
    ): void {
        $rows[] = [];
        $rows[] = ['TOP PERSONS BY REVENUE'];
        $rows[] = ['ID', 'Name', 'Revenue'];

        foreach ($items as $item) {
            $rows[] = [
                data_get($item, 'id'),

                $this->safeText(
                    data_get($item, 'name')
                ),

                core()->formatBasePrice(
                    (float) data_get($item, 'revenue', 0)
                ),
            ];
        }
    }

    /**
     * Menambahkan top products.
     */
    protected function appendTopProducts(
        array &$rows,
        Collection $items
    ): void {
        $rows[] = [];
        $rows[] = ['TOP PRODUCTS BY REVENUE'];
        $rows[] = [
            'ID',
            'Product',
            'Price',
            'Revenue',
        ];

        foreach ($items as $item) {
            $rows[] = [
                data_get($item, 'id'),

                $this->safeText(
                    data_get($item, 'name')
                ),

                core()->formatBasePrice(
                    (float) data_get($item, 'price', 0)
                ),

                core()->formatBasePrice(
                    (float) data_get($item, 'revenue', 0)
                ),
            ];
        }
    }

    /**
     * Mencegah formula injection pada Excel.
     */
    protected function safeText(mixed $value): string
    {
        $value = (string) ($value ?? '');

        if (preg_match('/^[=+\-@]/', $value)) {
            return "'".$value;
        }

        return $value;
    }
}