<?php

/*
|--------------------------------------------------------------------------
| Internal Chat V3.3.3 - Native Pin/Mute Final Hotfix
|--------------------------------------------------------------------------
|
| Root cause:
| Sidebar V3.3 is rebuilt every 4 seconds. Several generations of JS click
| listeners (V3.3, V3.3.1, V3.3.2) can therefore compete with controls that
| are constantly destroyed/re-created.
|
| Final strategy:
| - Pin / Unpin = REAL HTML POST form rendered inside each dynamic row.
| - Mute = modern modal containing ONE REAL HTML POST form.
| - No fetch() is used for Pin/Mute.
| - No click delegation is used for Pin.
| - No title parsing is used to discover conversation id.
| - Exact preference URL is generated by Laravel route(), then conversation id
|   is inserted into that URL.
|
| This installer patches only the current chat Blade renderer.
| The package also supplies the dedicated V3.3.2 Conversation Controller so
| normal form POST receives a redirect back to chat.
|
| No migration / route / provider changes.
|
*/

$root =
    realpath(
        __DIR__.'/..'
    );

if (! $root) {
    fwrite(
        STDERR,
        "Project root tidak ditemukan.\n"
    );

    exit(1);
}

$blade =
    $root
    .'/packages/Webkul/Admin/src/Resources/views/internal-communication/chat.blade.php';

if (! is_file($blade)) {
    fwrite(
        STDERR,
        "chat.blade.php tidak ditemukan.\n"
    );

    exit(2);
}

$source =
    file_get_contents(
        $blade
    );

if ($source === false) {
    fwrite(
        STDERR,
        "chat.blade.php tidak dapat dibaca.\n"
    );

    exit(3);
}

if (
    str_contains(
        $source,
        'INTERNAL CHAT V3.3.3 NATIVE PIN MUTE'
    )
) {
    echo "[SKIP] Internal Chat V3.3.3 already installed.\n";

    exit(0);
}

$required = [
    'INTERNAL CHAT V3.3 CONVERSATION MANAGEMENT',
    'id="crm-wa-conversation-list"',
    'const renderSidebar =',
    'let refreshing =',
    'window.crmChatV33RefreshSidebar',
];

foreach ($required as $marker) {
    if (
        ! str_contains(
            $source,
            $marker
        )
    ) {
        fwrite(
            STDERR,
            "Current V3.3 Blade tidak dikenali: {$marker}\n"
            ."Patch dihentikan agar chat customized tidak rusak.\n"
        );

        exit(4);
    }
}

$backup =
    $blade
    .'.before-internal-chat-v3-3-3-native-pin-mute.bak';

if (! is_file($backup)) {
    if (
        ! copy(
            $blade,
            $backup
        )
    ) {
        fwrite(
            STDERR,
            "Gagal membuat backup chat Blade.\n"
        );

        exit(5);
    }
}

/*
|--------------------------------------------------------------------------
| Replace current renderSidebar, regardless of V3.3/V3.3.1 renderer variant.
|--------------------------------------------------------------------------
*/

$renderStart =
    strpos(
        $source,
        "            const renderSidebar = (\n"
    );

$renderEnd =
    $renderStart === false
        ? false
        : strpos(
            $source,
            "            let refreshing =\n",
            $renderStart
        );

if (
    $renderStart === false
    || $renderEnd === false
) {
    fwrite(
        STDERR,
        "renderSidebar block tidak ditemukan.\n"
    );

    exit(6);
}

$renderer = <<<'JS'
            /* INTERNAL CHAT V3.3.3 NATIVE PIN MUTE RENDERER */
            const renderSidebar = (
                rows
            ) => {
                if (! list) {
                    return;
                }

                const preferenceTemplate =
                    String(
                        document
                            .getElementById(
                                'crm-chat-v333-config'
                            )
                            ?.dataset
                            .preferenceTemplate
                        || ''
                    );

                const hardCsrf =
                    String(
                        document
                            .getElementById(
                                'crm-chat-v333-config'
                            )
                            ?.dataset
                            .csrf
                        || ''
                    );

                const preferenceUrl = (
                    conversationId
                ) =>
                    preferenceTemplate.replace(
                        '__CID__',
                        encodeURIComponent(
                            String(
                                conversationId
                            )
                        )
                    );

                const nativePreferenceForm = (
                    conversationId,
                    action,
                    label,
                    title
                ) => {
                    const form =
                        document.createElement(
                            'form'
                        );

                    form.method =
                        'POST';

                    form.action =
                        preferenceUrl(
                            conversationId
                        );

                    form.style.margin =
                        '0';

                    form.style.padding =
                        '0';

                    form.addEventListener(
                        'click',
                        (event) => {
                            event.stopPropagation();
                        }
                    );

                    const token =
                        document.createElement(
                            'input'
                        );

                    token.type =
                        'hidden';

                    token.name =
                        '_token';

                    token.value =
                        hardCsrf;

                    const actionInput =
                        document.createElement(
                            'input'
                        );

                    actionInput.type =
                        'hidden';

                    actionInput.name =
                        'action';

                    actionInput.value =
                        action;

                    const button =
                        document.createElement(
                            'button'
                        );

                    button.type =
                        'submit';

                    /*
                     * Deliberately avoid titles used by old V3.3.2 capture
                     * listener: "pin conversation" / "mute conversation".
                     */
                    button.title =
                        title;

                    button.textContent =
                        label;

                    button.style.cssText =
                        'width:26px;'
                        +'height:26px;'
                        +'display:flex;'
                        +'align-items:center;'
                        +'justify-content:center;'
                        +'padding:0;'
                        +'border:1px solid #e5e7eb;'
                        +'border-radius:8px;'
                        +'background:#ffffff;'
                        +'font-size:11px;'
                        +'cursor:pointer;';

                    form.appendChild(
                        token
                    );

                    form.appendChild(
                        actionInput
                    );

                    form.appendChild(
                        button
                    );

                    return form;
                };

                const fragment =
                    document.createDocumentFragment();

                rows.forEach(
                    (row) => {
                        const wrapper =
                            document.createElement(
                                'div'
                            );

                        wrapper.dataset.conversationSearch =
                            String(
                                row.name
                                +' '
                                +row.role
                                +' '
                                +row.preview
                            ).toLowerCase();

                        wrapper.style.cssText =
                            'display:flex;'
                            +'align-items:stretch;'
                            +'min-height:60px;'
                            +'border-bottom:1px solid #e5e7eb;'
                            +'background:'
                            +(
                                Number(row.id)
                                === activeConversation
                                    ? '#f8fafc'
                                    : '#ffffff'
                            )
                            +';';

                        const link =
                            document.createElement(
                                'a'
                            );

                        link.href =
                            conversationUrl(
                                row.id
                            );

                        link.style.cssText =
                            'min-width:0;'
                            +'flex:1 1 auto;'
                            +'display:flex;'
                            +'align-items:center;'
                            +'gap:9px;'
                            +'padding:8px 6px 8px 10px;'
                            +'text-decoration:none;'
                            +'color:inherit;';

                        const unread =
                            Number(
                                row.unread
                                || 0
                            );

                        const presenceColor =
                            row.online
                                ? '#22c55e'
                                : (
                                    row.idle
                                        ? '#f59e0b'
                                        : '#cbd5e1'
                                );

                        link.innerHTML =
                            '<div style="position:relative;flex:0 0 auto;">'
                            +'<div style="width:34px;height:34px;border-radius:50%;display:flex;align-items:center;justify-content:center;background:#f1f5f9;color:#334155;font-size:10px;font-weight:800;">'
                            +escapeHtml(
                                row.initials
                            )
                            +'</div>'
                            +'<span style="position:absolute;right:-1px;bottom:0;width:9px;height:9px;border:2px solid #fff;border-radius:50%;background:'
                            +presenceColor
                            +';"></span>'
                            +'</div>'
                            +'<div style="min-width:0;flex:1;">'
                            +'<div style="display:flex;align-items:center;justify-content:space-between;gap:7px;">'
                            +'<div style="min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px;font-weight:800;color:#0f172a;">'
                            +(
                                row.pinned
                                    ? '📌 '
                                    : ''
                            )
                            +escapeHtml(
                                row.name
                            )
                            +'</div>'
                            +'<div style="flex:0 0 auto;font-size:9px;color:#94a3b8;">'
                            +escapeHtml(
                                row.time
                            )
                            +'</div>'
                            +'</div>'
                            +'<div style="margin-top:1px;display:flex;align-items:center;gap:6px;">'
                            +'<div style="min-width:0;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:10.5px;line-height:14px;color:'
                            +(
                                unread > 0
                                    ? '#0f172a'
                                    : '#64748b'
                            )
                            +';font-weight:'
                            +(
                                unread > 0
                                    ? '700'
                                    : '500'
                            )
                            +';">'
                            +escapeHtml(
                                row.preview
                            )
                            +'</div>'
                            +(
                                unread > 0
                                    ? '<div style="flex:0 0 auto;min-width:18px;height:18px;padding:0 5px;border-radius:999px;display:flex;align-items:center;justify-content:center;background:#0f172a;color:#fff;font-size:9px;font-weight:800;">'
                                        +(
                                            unread > 99
                                                ? '99+'
                                                : unread
                                        )
                                        +'</div>'
                                    : ''
                            )
                            +'</div>'
                            +'<div style="margin-top:1px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:9px;line-height:12px;color:#94a3b8;">'
                            +escapeHtml(
                                row.role
                            )
                            +' · '
                            +'<span style="color:'
                            +(
                                row.online
                                    ? '#16a34a'
                                    : (
                                        row.idle
                                            ? '#d97706'
                                            : '#94a3b8'
                                    )
                            )
                            +';">'
                            +escapeHtml(
                                row.presence
                            )
                            +'</span>'
                            +(
                                row.muted
                                    ? ' · 🔕'
                                    : ''
                            )
                            +'</div>'
                            +'</div>';

                        const controls =
                            document.createElement(
                                'div'
                            );

                        controls.style.cssText =
                            'flex:0 0 auto;'
                            +'display:flex;'
                            +'align-items:flex-start;'
                            +'gap:4px;'
                            +'padding:8px 8px 0 0;';

                        /*
                         * PIN = native form submit. No fetch, no delegated click.
                         */
                        controls.appendChild(
                            nativePreferenceForm(
                                row.id,
                                row.pinned
                                    ? 'unpin'
                                    : 'pin',
                                row.pinned
                                    ? '📍'
                                    : '📌',
                                row.pinned
                                    ? 'Unpin'
                                    : 'Pin'
                            )
                        );

                        /*
                         * Mute only needs JS to open modal. Submission itself is
                         * a native form inside the modal.
                         */
                        const muteButton =
                            document.createElement(
                                'button'
                            );

                        muteButton.type =
                            'button';

                        muteButton.title =
                            row.muted
                                ? 'Muted options'
                                : 'Mute';

                        muteButton.textContent =
                            row.muted
                                ? '🔕'
                                : '🔔';

                        muteButton.style.cssText =
                            'width:26px;'
                            +'height:26px;'
                            +'display:flex;'
                            +'align-items:center;'
                            +'justify-content:center;'
                            +'padding:0;'
                            +'border:1px solid #e5e7eb;'
                            +'border-radius:8px;'
                            +'background:#ffffff;'
                            +'font-size:11px;'
                            +'cursor:pointer;';

                        muteButton.addEventListener(
                            'click',
                            (event) => {
                                event.preventDefault();
                                event.stopPropagation();

                                window.crmChatV333OpenMute(
                                    row.id,
                                    row.name,
                                    row.mute_label
                                    || ''
                                );
                            }
                        );

                        controls.appendChild(
                            muteButton
                        );

                        wrapper.appendChild(
                            link
                        );

                        wrapper.appendChild(
                            controls
                        );

                        fragment.appendChild(
                            wrapper
                        );
                    }
                );

                list.innerHTML =
                    '';

                list.appendChild(
                    fragment
                );

                if (search) {
                    search.dispatchEvent(
                        new Event(
                            'input'
                        )
                    );
                }
            };

JS;

$source =
    substr_replace(
        $source,
        $renderer,
        $renderStart,
        $renderEnd
        - $renderStart
    );

/*
|--------------------------------------------------------------------------
| Add exact route config + native mute form/modal.
|--------------------------------------------------------------------------
*/

$closing =
    '</x-admin::layouts>';

$closingPos =
    strrpos(
        $source,
        $closing
    );

if ($closingPos === false) {
    fwrite(
        STDERR,
        "Closing x-admin::layouts tidak ditemukan.\n"
    );

    exit(7);
}

$hardfix = <<<'BLADE'

    {{-- INTERNAL CHAT V3.3.3 NATIVE PIN MUTE --}}
    <div
        id="crm-chat-v333-config"
        data-preference-template="{{ route('admin.internal-chat.preference', ['conversationId' => '__CID__']) }}"
        data-csrf="{{ csrf_token() }}"
        style="display:none;"
    ></div>

    <div
        id="crm-chat-v333-mute-modal"
        style="
            display:none;
            position:fixed;
            inset:0;
            z-index:150;
            align-items:center;
            justify-content:center;
            padding:18px;
            background:rgba(15,23,42,.46);
            backdrop-filter:blur(3px);
        "
    >
        <form
            id="crm-chat-v333-mute-form"
            method="POST"
            action=""
            style="
                width:min(92vw,350px);
                overflow:hidden;
                border:1px solid #e5e7eb;
                border-radius:18px;
                background:#ffffff;
                box-shadow:0 28px 80px rgba(15,23,42,.26);
            "
        >
            @csrf

            <div style="padding:15px 16px;border-bottom:1px solid #e5e7eb;">
                <div style="font-size:15px;font-weight:800;color:#0f172a;">
                    Mute Conversation
                </div>

                <div
                    id="crm-chat-v333-mute-name"
                    style="margin-top:3px;font-size:12px;color:#64748b;"
                ></div>
            </div>

            <div style="padding:8px;">
                <button
                    type="submit"
                    name="action"
                    value="mute_1_hour"
                    style="width:100%;padding:10px 12px;text-align:left;border-radius:10px;"
                >
                    🔕 1 jam
                </button>

                <button
                    type="submit"
                    name="action"
                    value="mute_today"
                    style="width:100%;padding:10px 12px;text-align:left;border-radius:10px;"
                >
                    🔕 Sampai akhir hari
                </button>

                <button
                    type="submit"
                    name="action"
                    value="mute_forever"
                    style="width:100%;padding:10px 12px;text-align:left;border-radius:10px;"
                >
                    🔕 Sampai diaktifkan kembali
                </button>

                <button
                    type="submit"
                    name="action"
                    value="unmute"
                    style="width:100%;padding:10px 12px;text-align:left;border-radius:10px;"
                >
                    🔔 Unmute
                </button>
            </div>

            <div
                style="
                    display:flex;
                    align-items:center;
                    justify-content:flex-end;
                    padding:10px 16px;
                    border-top:1px solid #e5e7eb;
                "
            >
                <button
                    type="button"
                    id="crm-chat-v333-mute-close"
                    class="secondary-button"
                >
                    Close
                </button>
            </div>
        </form>
    </div>

    <script>
        (() => {
            const config =
                document.getElementById(
                    'crm-chat-v333-config'
                );

            const modal =
                document.getElementById(
                    'crm-chat-v333-mute-modal'
                );

            const form =
                document.getElementById(
                    'crm-chat-v333-mute-form'
                );

            const name =
                document.getElementById(
                    'crm-chat-v333-mute-name'
                );

            if (
                ! config
                || ! modal
                || ! form
            ) {
                return;
            }

            const template =
                String(
                    config.dataset.preferenceTemplate
                    || ''
                );

            const preferenceUrl = (
                conversationId
            ) =>
                template.replace(
                    '__CID__',
                    encodeURIComponent(
                        String(
                            conversationId
                        )
                    )
                );

            window.crmChatV333OpenMute =
                function (
                    conversationId,
                    conversationName,
                    muteLabel
                ) {
                    form.action =
                        preferenceUrl(
                            conversationId
                        );

                    if (name) {
                        name.textContent =
                            String(
                                conversationName
                                || 'Conversation'
                            )
                            +(
                                muteLabel
                                    ? ' · '
                                        +muteLabel
                                    : ''
                            );
                    }

                    modal.style.display =
                        'flex';

                    return false;
                };

            const close =
                () => {
                    modal.style.display =
                        'none';

                    form.action =
                        '';
                };

            document
                .getElementById(
                    'crm-chat-v333-mute-close'
                )
                .addEventListener(
                    'click',
                    close
                );

            modal.addEventListener(
                'click',
                (event) => {
                    if (
                        event.target
                        === modal
                    ) {
                        close();
                    }
                }
            );
        })();
    </script>

BLADE;

$source =
    substr_replace(
        $source,
        $hardfix,
        $closingPos,
        0
    );

if (
    file_put_contents(
        $blade,
        $source
    ) === false
) {
    copy(
        $backup,
        $blade
    );

    fwrite(
        STDERR,
        "Gagal menulis V3.3.3 Blade. Backup dipulihkan.\n"
    );

    exit(8);
}

$written =
    file_get_contents(
        $blade
    );

$postChecks = [
    'INTERNAL CHAT V3.3.3 NATIVE PIN MUTE',
    'INTERNAL CHAT V3.3.3 NATIVE PIN MUTE RENDERER',
    'data-preference-template=',
    'nativePreferenceForm',
    "form.method =\n                        'POST'",
    'crm-chat-v333-mute-form',
    'name="action"',
    'value="mute_1_hour"',
    'window.crmChatV333OpenMute',
];

foreach ($postChecks as $marker) {
    if (
        $written === false
        || ! str_contains(
            $written,
            $marker
        )
    ) {
        copy(
            $backup,
            $blade
        );

        fwrite(
            STDERR,
            "Post-write validation gagal: {$marker}\n"
            ."Backup dipulihkan otomatis.\n"
        );

        exit(9);
    }
}

echo "[PASS] Pin/Unpin converted to native HTML POST forms.\n";
echo "[PASS] Mute/Unmute converted to native HTML POST modal form.\n";
echo "[PASS] Exact preference route template generated by Laravel route().\n";
echo "[PASS] Dynamic conversation IDs embedded directly into form actions.\n";
echo "[PASS] Old Pin/Mute click-listener dependency removed from final controls.\n";
echo "[PASS] No migration / route / provider changes.\n";
